import Head from "next/head";

export default function Home() {

  return (
    <div>
      <Head>
        <title>Draw Together</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="h-screen">
        <h1 className="text-red-600">Hi meow, Let s Draw together.</h1>
        <div className=" h-[80vh] flex flex-col items-center justify-center">
            <h1 className="text-red-600">This feature will come soon.</h1>
        </div>
      </main>

      <footer></footer>
    </div>
  );
}
