import Head from 'next/head'


export default function Home() {
    return (
        <div>
            <Head>
                <title>Audio</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <main >
                <div className='text-red-600'>
                    This is a Motivational Site. Motivated from Meow.
                </div>
            </main>
        </div>
    )
}
