import Head from 'next/head'
import { useEffect, useState } from 'react'
import socketClient from "socket.io-client";
const SERVER = "http://192.168.0.106:4001";


export default function Home() {
    let [socket, setSocket] = useState<{ [key: string]: any }>({});
    let [audio, setAudio] = useState<{ [key: string]: any }>({});
    useEffect(() => {
        const io = socketClient(SERVER);
        setSocket(io);
        setAudio(new Audio());
    }, [setSocket]);


    return (
        <div>
            <Head>
                <title>Audio</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <main >
                <div className='text-red-600'>
                    This is a Motivational Site. Motivated from Meow.
                </div>
            </main>
        </div>
    )
}
