import Head from 'next/head'
import { useEffect, useState } from 'react'
import socketClient from "socket.io-client";
import Layout from "./_layout";
const SERVER = "http://192.168.0.106:4001";


export default function Home() {
  let [socket, setSocket] = useState<{[key: string]: any}>({});
  let [audio, setAudio] = useState<{[key: string]: any}>({});
  useEffect(() => {
    const io = socketClient(SERVER);
    setSocket(io);
    setAudio(new Audio());
  }, [setSocket]);


  return (
    <div>
      <Head>
        <title>Audio</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main >
        <h1 className='text-red-600'>
          This is a homepage.
        </h1>
        {/* <button onClick={() => {
          console.log("===clicked");
          socket.emit('getAudioFile', "");
          socket.on("playAudio", (file: any) => {
            console.log("==============");
            console.log("===", file);
            audio.src = `data:audio/mp3;base64,${file.data}`;
            audio.play();
          });
        }}> play </button> */}

      </main>

      <footer>
      </footer>
    </div>
  )
}
