import Head from 'next/head'

export default function Home() {
  
  return (
    <div>
      <Head>
        <title>Audio</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main >
        <h1 className='text-red-600'>
          This is a homepage.
        </h1>
        {/* <button onClick={() => {
          console.log("===clicked");
          socket.emit('getAudioFile', "");
          socket.on("playAudio", (file: any) => {
            console.log("==============");
            console.log("===", file);
            audio.src = `data:audio/mp3;base64,${file.data}`;
            audio.play();
          });
        }}> play </button> */}

      </main>

      <footer>
      </footer>
    </div>
  )
}
