import Head from "next/head";
import Link from "next/link";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Audio</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <h1 className="text-red-600 mb-10">Hi, Welcome to the Dashboard.</h1>
        <div className="flex flex-row justify-around flex-wrap	">
          <div className="h-[80px] w-[100px] bg-green-400 flex flex-col justify-center items-center mb-10 rounded-lg drop-shadow-2xl">
            <Link href={"/dashboard/audio"}>Audio</Link>
          </div>
          <div className="h-[80px] w-[100px] bg-green-400 flex flex-col justify-center items-center mb-10 rounded-lg drop-shadow-2xl">
            <Link href={"/dashboard/video"}>Video</Link>
          </div>
          <div className="h-[80px] w-[100px] bg-green-400 flex flex-col justify-center items-center mb-10 rounded-lg drop-shadow-2xl">
            <Link href={"/dashboard/drawing"}>Drawing</Link>
          </div>
        </div>
      </main>

      <footer></footer>
    </div>
  );
}
