import Head from "next/head";
import { useEffect, useState } from "react";
import socketClient from "socket.io-client";
import PlayArrowIcon from "@mui/icons-material/PlayArrow";
import PauseIcon from "@mui/icons-material/Pause";
const SERVER = process.env.NEXT_PUBLIC_APP_SOCKET_SERVER || "";


export default function Home() {
  let [socket, setSocket] = useState<{ [key: string]: any }>({});
  let [audio, setAudio] = useState<{ [key: string]: any }>({});
  const [playAudio, setPlayAudio] = useState(false);
  const [log, setLog] = useState("init");
  const [audioFile, setAudioFile] = useState<{ [key: string]: any }>({});
  useEffect(() => {
    if(!SERVER) {
         setLog("Server is in sleep");
    } else {
        const io = socketClient(SERVER);
        setSocket(io);
        setLog("Connected");
        setAudio(new Audio());
        console.log("=====Iam changed");
        io.on("playAudio", (file: any) => {
          setAudioFile(file);
          audio.src = `data:audio/mp3;base64,${audioFile.data}`;
          setLog("ready to play");
        });
        io.on("pause", ()=>{
            setLog("pause");
            console.log("==I am recieved");
            setPlayAudio(false)
        })
        io.on("play", ()=>{
            setLog("playing");
            console.log("==I am recieved");
            setPlayAudio(true)
        })
    }
  }, []);

  useEffect(() => {
    console.log("==changed==", socket.emit);
    if (socket.emit) {
      socket.emit("getAudioFile", "");
    }
  }, [socket]);

  useEffect(() => {
    if (audioFile.data && audio) {
      audio.src = `data:audio/mp3;base64,${audioFile.data}`;
      console.log("===File loaded & set to play");
    }
  }, [audioFile, audio]);

  return (
    <div>
      <Head>
        <title>Listen Together</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="h-screen">
        <h1 className="text-red-600 mb-10">Hi, Welcome to the Meow.</h1>
        <div className="h-[80vh] ">
          <div className="h-[40vh]  flex flex-col justify-around items-center">
            <h1 className="">song name</h1>
            <div className="h-[180px]  w-[180px] bg-red-50 rounded-full mb-4 drop-shadow-2xl flex justify-center items-center">
              {!playAudio && (
                <PlayArrowIcon
                  onClick={() => {
                    console.log("===I am clicked", audio);
                    socket.emit("play");
                    audio.play();
                    setPlayAudio(true);
                  }}
                  fontSize="large"
                />
              )}
              {playAudio && (
                <PauseIcon
                  onClick={() => {
                    audio.pause();
                    socket.emit("pause");
                  }}
                  fontSize="large"
                />
              )}
            </div>
            {log}
          </div>
          <div className="h-[40vh] "></div>
        </div>
      </main>
    </div>
  );
}
